# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('dish', models.CharField(max_length=200)),
                ('main_ingredient', models.CharField(max_length=200)),
                ('other_ingredients', models.CharField(max_length=500)),
            ],
        ),
    ]
